pass/myaccount/urls.py
from django.conf.urls import url

from . import views


app_name = 'myaccount'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new_visit/$', views.new_visit, name='new_visit'),
    url(r'^add_visit/$', views.add_visit, name='add_visit'),
    url(r'^edit_entry/$', views.edit_entry, name='edit_entry'),
    url(r'^make_entry/$', views.make_entry, name='make_entry'),
    url(r'^show_entry/$', views.show_entry, name='show_entry'),
]

pass/pass/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', include('register.urls')),
    url(r'^myaccount/', include('myaccount.urls'))
]

pass/register/urls.py
from django.conf.urls import url

from . import views


app_name = 'register'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_page, name='login'),
    url(r'^logout/$', views.logout_page, name='logout'),
]

pass/myaccount/models.py
from django.db import models

# Create your models here.

pass/register/models.py
import datetime    

from django.utils.timezone import now
from django.contrib.auth.models import User

from django.db import models

# Create your models here.


class Visit(models.Model):

    created   = models.DateTimeField('date created', auto_now_add=True)
    user      = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f"{str(self.user)}'s visit at {str(self.created)}"


class Entry(models.Model):

    doctor_first_name  = models.CharField(max_length=300)
    doctor_last_name  = models.CharField(max_length=300)
    hospital = models.CharField(max_length=300)

    visit     = models.ForeignKey(Visit, on_delete=models.PROTECT)
    created   = models.DateField('date created', auto_now_add=True)
    date_visit = models.DateField('date visit')
    doctor_note = models.TextField()
    edit_note  = models.TextField(default='new note')

    def __str__(self):
        return f"{str(self.created)} - {str(self.doctor_note)}"


class Medication(models.Model):

    TYPES = [
        ('surgery', 'surgery'),
        ('prescription', 'prescription'),
        ('other', 'other')
    ]

    entry           = models.ForeignKey(Entry, on_delete=models.PROTECT, default=None)
    identification  = models.CharField(max_length=500)
    medication_name = models.CharField(max_length=500)
    medication_type = models.CharField(max_length=500, choices=TYPES) 
    description     = models.TextField()
    
    models.ForeignKey(Entry, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.medication_name)

pass/myaccount/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect


from register.models import Entry, Visit
# Create your views here.

@login_required
def index(request):
    return render(request, 'myaccount/index.html', { 'user' : request.user })

@login_required
def add_visit(request):
    print("adding visit")
    return render(request, 'myaccount/addvisit.html', { 'username' : request.user.username })

@login_required
def new_visit(request):
    visit = request.user.visit_set.create()
    dictionary = request.POST.dict()
    print(dictionary)
    dictionary['visit_id'] = visit.id
    create_entry(request, dictionary)
    return HttpResponseRedirect('/myaccount/')



@login_required
def edit_entry(request):
    visit_id = request.GET['visit_id']
    visit = Visit.objects.get(id=request.GET['visit_id'])

    entry = visit.entry_set.last()
    username = request.user.username
    return render(request, 'myaccount/editentry.html', {
        'entry' : entry,
        'visit_id': visit_id,
        'username': username
    })


@login_required
def make_entry(request):
    return create_entry(request, request.POST.dict())
    

def create_entry(request, dictionary):
    visit = Visit.objects.get(id=dictionary['visit_id'])
    entry = visit.entry_set.create(
        doctor_note       = dictionary['doctor_note'],
        doctor_first_name = dictionary['doctor_first_name'],
        doctor_last_name  = dictionary['doctor_last_name'],
        hospital          = dictionary['hospital'],
        date_visit        = dictionary['date_visit'],
        edit_note         = dictionary['edit_note'])
    visit.save()
    entry.save()
    return HttpResponseRedirect('/myaccount/')
    

def show_entry(request):
    visit = Visit.objects.get(id=request.GET['visit_id'])
    return render(request, 'myaccount/showentry.html', {
        'visit' : visit
    })

pass/register/views.py
from django.contrib.auth import authenticate, login, logout

from django.db import IntegrityError

from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User


def index(request):
    return render(request, 'register/index.html')


def login_page(request):
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        success = True
    else:
        success = False

    return render(request, 'register/loggedin.html', {
        'username': username, 
        'success' : success
    })


def register(request):
    return render(request, 'register/register.html')


def submit(request):
    email    = request.POST['email']
    username = request.POST['username']
    password = request.POST['password']

    fname    = request.POST['fname']
    lname    = request.POST['lname']

    try:
        user = User.objects.create_user(
                email=email,
                username=username,
                password=password,
                first_name=fname,
                last_name=lname)

        user.save()

        success = True

    except IntegrityError:
        success = False

    if 'next' in request.POST:
        return HttpResponseRedirect(request.POST['next'])
    else:
        return render(request, 'register/index.html')


def logout_page(request):
    username = request.user.username
    logout(request)
    return render(request, 'register/loggedout.html', {'username' : username } )

pass/myaccount/templates/myaccount/addvisit.html
<h1>Add Visit for {{ username }}</h1>


<form action="{% url 'myaccount:new_visit' %}" method="post">
    {% csrf_token %}

    <br> doctor's first name : <input type="text" name="doctor_first_name">
    <br> doctor's last name : <input type="text"  name="doctor_last_name">
    <br> hospital : <input type="text"  name="hospital">
    <br> date of visit: <input type="date" name="date_visit">
    <br> doctor's note: <input type="textarea" name="doctor_note">

    <input type="hidden" value="first note" name="edit_note">
    <br><input type="submit" value="Submit">
</form>

pass/myaccount/templates/myaccount/editentry.html
<h1>Entry Edit for {{ username }}</h1>


<form action="{% url 'myaccount:make_entry' %}" method="post">
    {% csrf_token %}

    <br> doctor's first name : <input type="text" name="doctor_first_name" value="{{ entry.doctor_first_name }}">
    <br> doctor's last name : <input type="text"  name="doctor_last_name" value="{{ entry.doctor_last_name }}">
    <br> hospital : <input type="text"  name="hospital" value="{{ entry.hospital }}">
    <br> date of visit: <input type="date" name="date_visit" value="{{ entry.date_visit }}">
    <br> edit note: <input type="textarea" name="edit_note" value="">
    <br> doctor's note: <input type="textarea" name="doctor_note" value="{{ entry.doctor_note }}">

    <input type="hidden" value="{{ visit_id }}" name="visit_id">
    <br><input type="submit" value="Submit">
</form>

pass/myaccount/templates/myaccount/index.html
{{ user.first_name }} {{ user.last_name }}

<form action="{% url 'myaccount:add_visit' %}" method="get">
    <input type="submit" value="New Visit">
</form>

{% for visit in user.visit_set.all %}

    <br>    Created: {{ visit.entry_set.last.created }} 
    <br>    Doctor: {{ visit.entry_set.last.doctor_first_name }} {{ visit.entry_set.last.doctor_last_name }}
    <br>    Hospital: {{ visit.entry_set.last.hospital }} 
    <br>    Date: {{ visit.entry_set.last.date_visit }}
    <br>    Diagnosis: {{ visit.entry_set.last.doctor_note }}
    <br>    Note: {{ visit.entry_set.last.edit_note }}
    <br>    - Medications
    <br>        {% for med in visit.entry_set.last.medication_set.all %} 
    <br>
    <br>            Identification: {{ med.identification }}
    <br>            Name: {{ med.medication_name }}
    <br>            Description: {{ med.description }}
    <br>            Type: {{ med.medication_type }}
                {% endfor %}
    <form action="{% url 'myaccount:edit_entry' %}" method="get">
        <input type='hidden' name="visit_id" value="{{ visit.id }}" />
        <input type="submit" value="Edit Entry">
    </form>

    <form action="{% url 'myaccount:show_entry' %}" method="get">
        <input type='hidden' name="visit_id" value="{{ visit.id }}" />
        <input type="submit" value="Show All Edits">
    </form>

{% endfor %}

pass/myaccount/templates/myaccount/showentry.html
{% for entry in visit.entry_set.all %}

    <br>    Created: {{ entry.created }} 
    <br>    Doctor: {{ entry.doctor_first_name }} {{ entry.doctor_last_name }}
    <br>    Hospital: {{ entry.hospital }} 
    <br>    Date: {{ entry.date_visit }}
    <br>    Diagnosis: {{ entry.doctor_note }}
    <br>    Note: {{ entry.edit_note }}
    <br>    - Medications
    <br>        {% for med in entry.medication_set.all %} 
    <br>
    <br>            Identification: {{ med.identification }}
    <br>            Name: {{ med.medication_name }}
    <br>            Description: {{ med.description }}
    <br>            Type: {{ med.medication_type }}
                {% endfor %}
    <form action="{% url 'myaccount:edit_entry' %}" method="get">
        <input type='hidden' name="visit_id" value="{{ visit.id }}" />
        <input type="submit" value="Edit Entry">
    </form>

    <form action="{% url 'myaccount:show_entry' %}" method="get">
        <input type='hidden' name="visit_id" value="{{ visit.id }}" />
        <input type="submit" value="Show All Edits">
    </form>

{% endfor %}

pass/register/templates/register 2/complete.html
<!DOCTYPE html>
<html>
<head>
<style>
.center {
    text-align: center;
    color: black;
    font-family: "Century Gothic", Times, serif;
    border: 5px solid black;
    border-radius: 18px;
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
    padding-top: 50px;
    padding-right: 30px;
    padding-bottom: 50px;
    padding-left: 80px;
    background-color: white;
}

body {
    background-image: url("doctorimage.jpg");
}
</style>
</head>
<body>
{% if success %}
    <h1 class="center">Congratulations, {{ username }} is registered!</h1>
{% else %}
    <h1 class="center">It seems like the user already exists.</h1>
{% endif %}
</body>
</html>

pass/register/templates/register 2/index.html
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("doctorimage.jpg");
}
.centered{
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
div.title {
    padding: 7px 50px;
    margin: auto;
    background-color: rgba(0,0,0,0.5);
    width: 575px;
    height: 360px;    
    padding: 10px;
    border: 5px solid white;
    color: white;
    text-align: center
}
.titletext{

   font-family: Arial Black;
   font-size: 85px;
   font-style: italic;
   font-weight: bold;
}
.catchph{
   font-family: Verdana, Geneva, sans-serif;
   font-size: 18px;
   font-style: oblique;
}

.button {
    margin: 20px auto; 
    width: 575px;
    background-color: #0094ff;
    color: white;
    padding: 12px 50px;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
.button:hover{
    background-color:#77c6ff
}

table, th, td {
    border: 0px;
    border-collapse: collapse;
}
th, td {
    padding: 17px;
}

input[type=submit] {
    width: 350px;
    background-color: #4CAF50;
    color: white;
    padding: 7px 10px;

    border: none;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
input[type=submit]:hover{
    background-color:#70ff75
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}
/* Modal Content/Box */
.modal-content {
    margin: 5px auto; /* 15% from the top and centered */
    padding: 7px 50px;
    background-color: rgba(0,0,0,0.5);
    width: 450px;
    height: 200px;    
    border: 5px solid white;
    color: white;
    text-align: center
}

/* The Close Button */
.close {
    /* Position it in the top right corner outside of the modal */
    position: absolute;
    right: 25px;
    top: 0; 
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

/* Close button on hover */
.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}


</style>
<title> Log in - ChronoLog, Your Personal Medical Passport</title>
</head>
<body>

<!-- Title & Log in Button -->
<div class = "centered">
<div class = "title">
<p class = "titletext">ChronoLog.</p>
<p class = "catchph">Your Personal Medical Passport.</p>

<<!-- Button to open the modal login form -->
<button class="button" onclick="document.getElementById('id01').style.display='block'">
LOG IN</button>

</div>
</div>

<div id="id01" class="modal">
<span onclick="document.getElementById('id01').style.display='none'" 
class="close" title="Close Modal">&times;</span>

<!-- Modal Content -->
<form class="modal-content animate" action="/action_page.php">
<form action="{% url 'register:login' %}" method="post">
<table style ="width:100%">
{% csrf_token %} <br> 
<tr>
  <th align="right">
  Username: 
  </th>
  <th align="left">
  <input type="text" name="userame"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Password: 
  </th>
  <th align="left">
  <input type="text" name="password">
  </th>
</tr>
</table>
<input type="submit" value="Submit"></form>
</form>
</div>



</body>
</html>

pass/register/templates/register 2/loggedin.html
<!DOCTYPE html>
<html>
<head>
<style>
.center {
    text-align: center;
    color: black;
    font-family: "Century Gothic", Times, serif;
    border: 5px solid black;
    border-radius: 18px;
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
    padding-top: 50px;
    padding-right: 30px;
    padding-bottom: 50px;
    padding-left: 80px;
    background-color: white;
  }


body {
    background-image: url("doctorimage.jpg");
}

</style>
</head>
<body>
{% if success %}
    <h1 class="center">Logged in as {{ username }}. </h1>
{% else %}
    <h1 class="center">There was a problem logging in as {{ username }}.</h1>
{% endif %}

</body>
</html>

pass/register/templates/register 2/loggedout.html
<h1> logged out from {{ username }} </h1>

pass/register/templates/register 2/register.html
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("doctorimage.jpg");
}
div.title {
    margin: auto;
    width: 600px;
    border: 5px solid rgba(255,255,255,1);
    background-color: rgba(0,0,0,0.45);
    color: white;
}

.custom {
	font-family: Century Gothic;
	font-size:50px;
}
h1{
	font-family: Century Gothic;
	font-size:53px;
 	text-align: center;  
}
.menu {
    padding: 7px 10px;
    margin: 10px auto;
    background-color: rgba(0,0,0,0.5);
    width: 400px;
    height: 520px;    
    padding: 10px;
    border: 5px solid white;
    font-family: Candara;
    color: white;
    font-size:20px;
}

table, th, td {
    border: 0px;
    border-collapse: collapse;
}
th, td {
    padding: 17px;
}

input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 7px 10px;

    border: none;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
input[type=submit]:hover{
    background-color:#70ff75
}

</style>
</head>
<body>
<div class = "title"><h1>Register</h1></div>
<div class = "menu">
<table style ="width:100%">
<form action="{% url 'register:submit' %}" method="post">
{% csrf_token %} <br> 
<tr>
  <th align="right">
  E-Mail: 
  </th>
  <th align="left">
  <input type="text" name="email"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Username: 
  </th>
  <th align="left">
  <input type="text" name="username">
  </th>
</tr>
<tr>
  <th align="right">
  Password: 
  </th>
  <th align="left">
  <input type="text" name="password"><br>
  </th>
</tr>
<tr>
  <th align="right">
  First Name: 
  </th>
  <th align="left">
  <input type="text" name="fname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Middle Name: 
  </th>
  <th align="left">
  <input type="text" name="mname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Last Name: 
  </th>
  <th align="left">
  <input type="text" name="lname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Usertype: 
  </th>
  <th align="left">
  <input type="radio" name="usertype" value="doctor" checked> Doctor 
  <input type="radio" name="usertype" value="user"> User<br>
  </th>
</tr>
</table> 
<br>
<input type="submit" value="Submit"><b>
{% if failure %}
<br>credentials not recognized<br>
{% endif %}
</form>
</div>
</body>


pass/register/templates/register/complete.html
<!DOCTYPE html>
<html>
<head>
<style>
.center {
    text-align: center;
    color: black;
    font-family: "Century Gothic", Times, serif;
    border: 5px solid black;
    border-radius: 18px;
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
    padding-top: 50px;
    padding-right: 30px;
    padding-bottom: 50px;
    padding-left: 80px;
    background-color: white;
}

body {
    background-image: url("doctorimage.jpg");
}
</style>
</head>
<body>
{% if success %}
    <h1 class="center">Congratulations, {{ username }} is registered!</h1>
{% else %}
    <h1 class="center">It seems like the user already exists.</h1>
{% endif %}
</body>
</html>

pass/register/templates/register/index.html
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("doctorimage.jpg");
}
.centered{
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
div.title {
    padding: 7px 50px;
    margin: auto;
    background-color: rgba(0,0,0,0.5);
    width: 575px;
    height: 360px;    
    padding: 10px;
    border: 5px solid white;
    color: white;
    text-align: center
}
.titletext{

   font-family: Arial Black;
   font-size: 85px;
   font-style: italic;
   font-weight: bold;
}
.catchph{
   font-family: Verdana, Geneva, sans-serif;
   font-size: 18px;
   font-style: oblique;
}

.button {
    margin: 20px auto; 
    width: 575px;
    background-color: #0094ff;
    color: white;
    padding: 12px 50px;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
.button:hover{
    background-color:#77c6ff
}

table, th, td {
    border: 0px;
    border-collapse: collapse;
}
th, td {
    padding: 17px;
}

input[type=submit] {
    width: 350px;
    background-color: #4CAF50;
    color: white;
    padding: 7px 10px;

    border: none;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
input[type=submit]:hover{
    background-color:#70ff75
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}
/* Modal Content/Box */
.modal-content {
    margin: 5px auto; /* 15% from the top and centered */
    padding: 7px 50px;
    background-color: rgba(0,0,0,0.5);
    width: 450px;
    height: 200px;    
    border: 5px solid white;
    color: white;
    text-align: center
}

/* The Close Button */
.close {
    /* Position it in the top right corner outside of the modal */
    position: absolute;
    right: 25px;
    top: 0; 
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

/* Close button on hover */
.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}


</style>
<title> Log in - ChronoLog, Your Personal Medical Passport</title>
</head>
<body>

<!-- Title & Log in Button -->
<div class = "centered">
<div class = "title">
<p class = "titletext">ChronoLog.</p>
<p class = "catchph">Your Personal Medical Passport.</p>

<<!-- Button to open the modal login form -->
<button class="button" onclick="document.getElementById('id01').style.display='block'">
LOG IN</button>

</div>
</div>

<div id="id01" class="modal">
<span onclick="document.getElementById('id01').style.display='none'" 
class="close" title="Close Modal">&times;</span>

<!-- Modal Content -->
<form class="modal-content animate" action="/action_page.php">
<form action="{% url 'register:login' %}" method="post">
<table style ="width:100%">
{% csrf_token %} <br> 
<tr>
  <th align="right">
  Username: 
  </th>
  <th align="left">
  <input type="text" name="userame"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Password: 
  </th>
  <th align="left">
  <input type="text" name="password">
  </th>
</tr>
</table>
<input type="submit" value="Submit"></form>
</form>
</div>



</body>
</html>

pass/register/templates/register/loggedin.html
<!DOCTYPE html>
<html>
<head>
<style>
.center {
    text-align: center;
    color: black;
    font-family: "Century Gothic", Times, serif;
    border: 5px solid black;
    border-radius: 18px;
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
    padding-top: 50px;
    padding-right: 30px;
    padding-bottom: 50px;
    padding-left: 80px;
    background-color: white;
  }


body {
    background-image: url("doctorimage.jpg");
}

</style>
</head>
<body>
{% if success %}
    <h1 class="center">Logged in as {{ username }}. </h1>
{% else %}
    <h1 class="center">There was a problem logging in as {{ username }}.</h1>
{% endif %}

</body>
</html>

pass/register/templates/register/loggedout.html
<h1> logged out from {{ username }} </h1>

pass/register/templates/register/register.html
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("doctorimage.jpg");
}
div.title {
    margin: auto;
    width: 600px;
    border: 5px solid rgba(255,255,255,1);
    background-color: rgba(0,0,0,0.45);
    color: white;
}

.custom {
	font-family: Century Gothic;
	font-size:50px;
}
h1{
	font-family: Century Gothic;
	font-size:53px;
 	text-align: center;  
}
.menu {
    padding: 7px 10px;
    margin: 10px auto;
    background-color: rgba(0,0,0,0.5);
    width: 400px;
    height: 520px;    
    padding: 10px;
    border: 5px solid white;
    font-family: Candara;
    color: white;
    font-size:20px;
}

table, th, td {
    border: 0px;
    border-collapse: collapse;
}
th, td {
    padding: 17px;
}

input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 7px 10px;

    border: none;
    cursor: pointer;
    height: 60px;
    font-size:20px;
    font-family: Century Gothic;
}
input[type=submit]:hover{
    background-color:#70ff75
}

</style>
</head>
<body>
<div class = "title"><h1>Register</h1></div>
<div class = "menu">
<table style ="width:100%">
<form action="{% url 'register:submit' %}" method="post">
{% csrf_token %} <br> 
<tr>
  <th align="right">
  E-Mail: 
  </th>
  <th align="left">
  <input type="text" name="email"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Username: 
  </th>
  <th align="left">
  <input type="text" name="username">
  </th>
</tr>
<tr>
  <th align="right">
  Password: 
  </th>
  <th align="left">
  <input type="text" name="password"><br>
  </th>
</tr>
<tr>
  <th align="right">
  First Name: 
  </th>
  <th align="left">
  <input type="text" name="fname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Middle Name: 
  </th>
  <th align="left">
  <input type="text" name="mname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Last Name: 
  </th>
  <th align="left">
  <input type="text" name="lname"><br>
  </th>
</tr>
<tr>
  <th align="right">
  Usertype: 
  </th>
  <th align="left">
  <input type="radio" name="usertype" value="doctor" checked> Doctor 
  <input type="radio" name="usertype" value="user"> User<br>
  </th>
</tr>
</table> 
<br>
<input type="submit" value="Submit"><b>
{% if failure %}
<br>credentials not recognized<br>
{% endif %}
</form>
</div>
</body>
